### ISSUE TITLE
When invoked from non-project directory, local jars cause classpath to be generated always

### ISSUE THREAD

**Issue by cursive-ide** [borkdude/deps.clj#101]
When invoking deps.clj from a directory which is not the project root, `*dir*` can be bound to indicate to the script which directory the project is in. If a deps.edn files contains local jars added as follows:
```clojure
{:paths ["local.jar"]}
```
then the classpath is always recalculated. The offending code is [here](https://github.com/cursive-ide/deps.clj/blob/77b3970e56f8811ff98c52337fa66a62de67f51f/deps.clj#L879-L880). If the path to the file is relative, it should be absolutised relative to `*dir*`.

**Comment by borkdude** [comment]
I think I've fixed it, but will re-open until you've provided a (programmatic) repro that we can include as a test.

**Comment by borkdude** [comment]
@cursive-ide Do you still have the repro for this? Just a bit of code would do, I can write the test for it.

**Comment by cursive-ide** [comment]
Sorry for the delay, #105 has a test for this. I checked that it fails with the old code and passes with the new version.
