### ISSUE TITLE
System deps.edn should be extracted on tools install

### ISSUE THREAD

**Issue by cursive-ide** [borkdude/deps.clj#106]
Currently, deps.clj detects whether the Clojure tools have been installed, and if not, downloads and installs them. If a client later uses the API to obtain the config paths, the first file in the list (the system deps) will not exist. This file exists in the tools distribution jar, but should be extracted on install. The standard Clojure tools do have this file available in their installation directory.

**Comment by borkdude** [comment]
@cursive-ide Isn't that what this piece of code is doing?

```
(let [config-deps-edn (io/file config-dir "deps.edn")
          example-deps-edn (io/file install-dir "example-deps.edn")]
      (when (and install-dir
                 (not (.exists config-deps-edn))
                 (.exists example-deps-edn))
        (io/copy example-deps-edn config-deps-edn)))
```

**Comment by borkdude** [comment]
I wonder if deps.clj should leave the `.clojure` directory alone, to not conflict with other installations.

**Comment by borkdude** [comment]
Ah, I didn't read the "on tools install" part

**Comment by borkdude** [comment]
Now the `clojure-tools-install!` requires one extra argument: `:config-dir`. When passed, it will extract the system deps.edn and tools dir tools.edn into that directory.
