### ISSUE TITLE
Handle relative paths for `CLJ_CONFIG`/`DEPS_CLJ_TOOLS_DIR`/`GITLIBS` correctly

### ISSUE THREAD

**Issue by dancmeyers** [borkdude/deps.clj#112]
When overriding the default values for `CLJ_CONFIG` (`~/.clojure`) or `DEPS_CLJ_TOOLS_DIR` (`~/.deps.clj/${VERSION}/ClojureTools`), relative paths are not correctly handled. I came across this because I want to build an uberjar of deps for a `bb` script on a remote executor (our CI pipeline) where I don't have access to the executing user's `${HOME}`, but you can replicate it easily enough:
```
➜ CLJ_CONFIG=bb-test/.clojure DEPS_CLJ_TOOLS_DIR=bb-test/.deps.clj GITLIBS=bb-test/.gitlibs bb -Sforce --config bb-test/bb.edn uberjar deps.jar
Error: Could not find or load main class clojure.main
Caused by: java.lang.ClassNotFoundException: clojure.main
Exception in thread "main" clojure.lang.ExceptionInfo:  babashka.process.Process@fb3b8914
	at babashka.process$check.invokeStatic(process.cljc:111)
	at babashka.process$shell.invokeStatic(process.cljc:651)
	<rest of stacktrace omitted>
```

The `CLJ_CONFIG` dir gets created, but it doesn't get correctly populated with a `.cpcache`:
```
➜ ls bb-test/.clojure
./        ../       deps.edn  tools/
```

The `DEPS_CLJ_TOOLS_DIR` seems to get populated correctly, but the same exception happens even if only it is relative, and `CLJ_CONFIG` is absolute.

If I use absolute paths, it works fine:
```
➜ CLJ_CONFIG=/Users/me/tmp/bb-test/.clojure DEPS_CLJ_TOOLS_DIR=/Users/me/tmp/bb-test/.deps.clj GITLIBS=/Users/me/tmp/bb-test/.gitlibs bb -Sforce --config bb-test/bb.edn uberjar deps.jar
{:warning "could not find classpath entry", :path "/Users/me/tmp/bb-test/.gitlibs/libs/org.babashka/spec.alpha/8df0712896f596680da7a32ae44bb000b7e45e68/src/main/java"}
{:warning "could not find classpath entry", :path "/Users/me/tmp/bb-test/.gitlibs/libs/org.babashka/spec.alpha/8df0712896f596680da7a32ae44bb000b7e45e68/src/main/resources"}

➜ ls bb-test/.clojure
./        ../       .cpcache/ deps.edn  tools/

➜ ls deps.jar
deps.jar
```

Of additional note, but I'm not sure if this is "working as intended", a relative `GITLIBS` _does_ work, but is relative from the location of the `bb.edn` config file provided, not from the working directory which `bb` is called from. So if you always run `bb` from one directory and specify a path to various different subdirectory `bb.edn` config files for different purposes, with the same dependences, you get those dependencies replicated multiple times across the filesystem instead of one central collection as you get with the default value.

**Comment by borkdude** [comment]
@dancmeyers I can't reproduce this issue with deps.clj.

```
borkdude@m1 ~/dev/babashka/deps.clj (master*?) $ rm -rf ~/.deps.clj
borkdude@m1 ~/dev/babashka/deps.clj (master*?) $ CLJ_CONFIG=bb-test/.clojure DEPS_CLJ_TOOLS_DIR=bb-test/.deps.clj GITLIBS=bb-test/.gitlibs ./deps.clj -Sforce -Sdeps '{:deps {medley/medley {:git/url "https://github.com/weavejester/medley" :git/sha "c5e6e39ac512518e43321cedff743a836b96f87e"}}}' -M -e "(require '[medley.core])"
:cache-dir ".cpcache"
```

Could you make a repro, perhaps per environment variable, so I can reproduce this and focus on fixing it per environment variable? The tools jar seems to be downloaded fine with a relative path, and GITLIBS is not something that deps.clj does anything with, so it's probably only CLJ_CONFIG that could be messing stuff up.

**Comment by dancmeyers** [comment]
@borkdude I feel like I'm going mad. I had a reliably failing command (what is in the original issue text), but now I can't make it fail on my machine. I'm really sorry for wasting your time... 

Also, I'm not sure what the `:cache-dir ".cpcache"` at the end of your example there is doing? It doesn't seem to be returned by the prior line when I run the same, but if I paste it with that line either my shell tries to interpret `:cache-dir` as a command (if I leave the newline in), which obviously fails, or if I delete the newline then I get an error from `clojure.main` trying to open `:cache-dir` (the keyword, not the argument to it) as a file.
