### ISSUE TITLE
Divergence with Clojure CLI script when determining default config directory

### ISSUE THREAD

**Issue by DerGuteMoritz** [borkdude/deps.clj#114]
As @jlesquembre [figured out](https://gist.github.com/jlesquembre/ad7cb8357fe13312eb23a437b87bcd2b), there is a divergence with how the Clojure CLI shell script constructs the default directory. This is caused by difference in how the user home directory is determined: `deps.clj` uses the `user.home` JVM property while the shell script uses the `HOME` environment variable. This has potentially different results on macOS (see link).

**Comment by borkdude** [comment]
Can you please summarize the issue here so I don't have to dig into external links? Also it would save me time if you could make explicit what is the current + expected behavior and if there should be a change somewhere, possibly with multiple alternative solutions.

**Comment by DerGuteMoritz** [comment]
The summary is in the description already: Because `deps.clj` and the shell script use different mechanisms to look up the user home directory, they can end up with different results. [Here](https://github.com/clojure/brew-install/blob/b03428b1b31a8d60573a284d6971fbd3db7b748d/src/main/resources/clojure/install/clojure#L280) you can see that the shell script uses `$HOME` while [`borkdude.deps/home-dir`](https://github.com/borkdude/deps.clj/blob/cc9ddf48625dbc29943a3f3fa4b9c54e19622eec/src/borkdude/deps.clj#L266) uses `(System/getProperty "user.home")`  which is not equivalent (see e.g. [JDK-8280357](https://bugs.openjdk.org/browse/JDK-8280357) for how this caused trouble in the past). The only fix I can see is to switch to `(System/getenv "HOME")` in `deps.clj`, we well, to exactly match the shell script's behavior (which AFAIUI is something that `deps.clj` strives to do). Hope that helps!

**Comment by DerGuteMoritz** [comment]
Oh yeah and we ran into this because the nix build environment on Darwin ends up with diverging results between the two in practice (see https://github.com/NixOS/nixpkgs/pull/257473#discussion_r1347796686).

**Comment by DerGuteMoritz** [comment]
If you agree, I can cook up a PR for this later, too!

**Comment by borkdude** [comment]
Please double-check how the CLI checks for the home dir on Windows.

**Comment by borkdude** [comment]
It seems in Windows `HOME` is probed and then `USERPROFILE`:

https://github.com/clojure/brew-install/blob/dabb82bd011b0510006dd88464f350052adb69b5/src/main/resources/clojure/install/ClojureTools.psm1#L254-L258

**Comment by borkdude** [comment]
let's make the change, PR welcome
