### ISSUE TITLE
Why isn't 1.11.1.1413 on the releases page?

### ISSUE THREAD

**Issue by jdjohnston** [borkdude/deps.clj#116]
The main page has it as the latest, but it's not on the releases page.

**Comment by borkdude** [comment]
What is "the releases page"?

**Comment by jdjohnston** [comment]
https://github.com/borkdude/deps.clj/releases

**Comment by borkdude** [comment]
That's very weird, I can see it, but not in an incognito screen
<img width="1435" alt="Screenshot 2023-10-17 at 20 59 03" src="https://github.com/borkdude/deps.clj/assets/284934/ffd8ed47-ffb1-4a42-8233-28bd373abc71">

**Comment by borkdude** [comment]
I updated the release and now it's visible , not sure what went wrong.
