### ISSUE TITLE
Why does 1.11.1.1429 require more CPU features than 1.11.1413?

### ISSUE THREAD

**Issue by jdjohnston** [borkdude/deps.clj#118]
My old laptop doesn't support some of the CPU features required by 1.11.1.1429, but 1.11.1.1413 runs fine.

My best guess would be a change in the build process, but does deps.clj _need_ the extra CPU features?

OTOH, I understand you don't want to live in the past. Please ignore if it's not practical to limit the build to only CPU features actually used.

**Comment by borkdude** [comment]
Please specify your operating system

**Comment by jdjohnston** [comment]
I was trying out the Windows build, but it's probably more a CPU (i7-2760QM) issue.

I haven't tried the Linux version yet. I have three versions of Linux as VirtualBoxes, so the same underlying CPU. Might be interesting.

**Comment by borkdude** [comment]
Yeah, I upgraded only the Windows build environment and know what
the problem is. I can fix this in the next release.

**Comment by jdjohnston** [comment]
I'll look forward to it! :) Thanks

I guess if I _really_ want to use 1.11.1.1429 on Windows, I'll use the standalone jar with`bb`

**Comment by borkdude** [comment]
You can also set `DEPS_CLJ_TOOLS_VERSION` to `1.11.1.1429` while using the previous version. I think this should work, although I recommend disabling that again from the next release on.

**Comment by borkdude** [comment]
@jdjohnston You can try the binary from this build to see if it's fixed now: https://ci.appveyor.com/project/borkdude/deps-clj/builds/48803645/artifacts

**Comment by jdjohnston** [comment]
Seems OK. `deps --version` ran without the insufficient CPU features error.

BTW, I'm working on a new issue. :) It's a problem on Windows, at least. Should be written-up soon.

**Comment by borkdude** [comment]
New release available

**Comment by jdjohnston** [comment]
@borkdude New release runs on my old laptop

**Comment by borkdude** [comment]
Thanks for confirming
