### ISSUE TITLE
Update to Clojure 1.12.0 / CLI 1.12.0.1479?

### ISSUE THREAD

**Issue by seancorfield** [borkdude/deps.clj#127]
Now that 1.12.0 is GA, what's the plan to bump `deps.clj`?

**Comment by borkdude** [comment]
Sure. can do tomorrow, I jhadn't noticed there was a new CLI version out

**Comment by seancorfield** [comment]
https://clojurians.slack.com/archives/C06MAR553/p1725572587342559 -- the only difference from 1.11.4.1474 is the change to use Clojure 1.12.0 instead of 1.11.4 by default.

**Comment by borkdude** [comment]
On this page https://github.com/clojure/brew-install/blob/1.12.0/CHANGELOG.md it says that the 1.12.0 release is a pre-release version, but this is probably just not updated yet? (cc @puredanger)
