### ISSUE TITLE
run-java-tool

### ISSUE THREAD

**Issue by joandste** [borkdude/deps.clj#129]
On Gentoo /usr/bin/java is a symlink to a bash script. It cannot be invoked directly and has to be used through it's symlink. Since the "which" function gets the canonical path it returns "/usr/libexec/eselect-java/run-java-tool.bash" and tries to use the script directly.

Using .getPath instead would fix the issue and behave closer to the unix command. (in bash "which java" returns "/usr/bin/java" on gentoo).

Checking JAVA_HOME first and then using "which" as the fallback would also work.

**Comment by borkdude** [comment]
I guess it's a similar issue to https://github.com/babashka/babashka/issues/1669?
The current solution to this would be to set `JAVA_CMD`.
But I think not resolving the symlink would be good since that's what happens in `clojure` as well.

**Comment by borkdude** [comment]
> Checking JAVA_HOME first and then using "which" as the fallback would also work.

I'm not doing this since this would deviate from the `clojure` script:

https://github.com/clojure/brew-install/blob/2ddadc972be51917afb1cea57d1c8c40478bd307/src/main/resources/clojure/install/clojure#L177

**Comment by borkdude** [comment]
@joandste Perhaps you're able to test the change on master which is supposed to fix this problem?

**Comment by joandste** [comment]
Problem is fixed using master, i tested it working on Gentoo.
