### ISSUE TITLE
Pass env var when using deps.clj as a clojure library

### ISSUE THREAD

**Issue by pfeodrippe** [borkdude/deps.clj#21]
Hi, I am using `deps.clj` as a library in my application and calling `borkdude.deps/-main` directly. 

Is there any way to pass a env var to it by other means besides calling from shell (some option which I could pass it, e. g. `-Senv CLJ_CACHE=some-path`)? I just want to pass a custom cache dir to it.

If there isn't, would a PR be welcomed? And if yes, what would be the preferred approach (it could be a a new `deps.clj` option or a dynamic var etc)?

Thanks, your library is a awesome project!!

**Comment by borkdude** [comment]
@pfeodrippe So in your application you need a way to pass the env var `CLJ_CACHE` to this library. Why don't you set the `CLJ_CACHE` env variable for your project? I'm trying to understand the use case better.

**Comment by pfeodrippe** [comment]
I'm making a standalone CLI application which creates a Clojure project and runs this created project with your library (see code below).

After building the JAR, it didn't work even with `CLJ_CACHE=my-path java -jar my-jar.jar` (maybe I'm doing something wrong?). Anyway, even if it worked, I would have to put it in another script (e.g. bash script) passing the ENV VAR, I would like to not have to pass ENV VAR when starting the application.

Maybe this is not a use case for this library, and I will undestand it =)

```clojure
(defn -main
  []
  (let [{:keys [:path]} (bean (fs/temp-dir "ummoi-"))
        _ (fs/mkdirs (str path "/src/ummoi_runner"))
        _ (fs/mkdirs (str path "/classes/tlc2/overrides"))
        deps-file (str path "/deps.edn")
        core-file (str path "/src/ummoi_runner/core.clj")]
    (spit deps-file (deps-config path))
    (spit core-file (core-form op-forms))
    (deps/-main "-Sdeps-file" deps-file "-m" "ummoi-runner.core"))
  (System/exit 0))
```

**Comment by borkdude** [comment]
@pfeodrippe I think that should work:

```
CLJ_CACHE=my-path java -jar my-jar.jar
```
but this environment variable is only respected when you don't have a `deps.edn` in your current working directory. If you do, then that directory is chosen as the cache directory.

**Comment by borkdude** [comment]
@pfeodrippe This is the relevant line in the source code:

https://github.com/borkdude/deps.clj/blob/64589845e014191b33d97cb1983dca504ba1dff2/src/borkdude/deps.clj#L373

I implemented this according to the `clojure` bash script. 

What is your use case for deviating from the current functionality?

**Comment by pfeodrippe** [comment]
@borkdude Hunnn, I didn't know about this, thanks!

I'm running `borkdude/deps` inside the project which create other Clojure projects. 

Running `borkdude/deps` inside the created projects instead should solve my problem (shame on me).

I was thinking from the wrong perspective, sorry for annoying you in a weekend :/

And thank you o/

**Comment by borkdude** [comment]
No problem at all.
