### ISSUE TITLE
Install scripts installing 0.0.8 instead of 0.0.9

### ISSUE THREAD

**Issue by lread** [borkdude/deps.clj#25]
While trying to distill a GitHub Actions windows failure, I switched from using scoop to `install.ps1` (usage as per README).  

I noticed that install.ps1 is installing v0.0.8 when the current release, I think, is [0.0.9](https://github.com/borkdude/deps.clj/releases/tag/v0.0.9).

I quick test of `install` on macOS gives same result of installing v0.0.8.

**Comment by borkdude** [comment]
Should be fixed now.

**Comment by lread** [comment]
Thanks!
