### ISSUE TITLE
Consider using faster download technique for install.ps1

### ISSUE THREAD

**Issue by lread** [borkdude/deps.clj#26]
I was troubleshooting an issue today, so ran `install.ps1` (as per README) many times.

I notice that `install.ps1` is using [Invoke-WebRequest ](https://github.com/borkdude/deps.clj/blob/95c71c92492b20cc83d4dc1f04841265e67f1a19/install.ps1#L35) to download 

A much faster (perhaps ~4x?) alternative is `System.Net.WebClient` [as described in this blog article](https://blog.jourdant.me/post/3-ways-to-download-files-with-powershell).  

Happy to PR if this is of interest to you.

**Comment by borkdude** [comment]
Sure!
