### ISSUE TITLE
deps.clj library jar is not usable

### ISSUE THREAD

**Issue by hugoduncan** [borkdude/deps.clj#28]
iiuc, trying to use deps.clj as a library from the jar currently does not work.

```clj
(require 'borkdude.deps)
```
gives a nil pointer exception trying to load `DEPS_CLJ_VERSION`.

**Comment by borkdude** [comment]
@hugoduncan Thanks. That's weird, since that file is part of the jar, at least on my filesystem:

```
$ jar -tf  /Users/borkdude/.m2/repository/borkdude/deps.clj/0.0.9/deps.clj-0.0.9.jar
META-INF/MANIFEST.MF
META-INF/maven/borkdude/deps.clj/pom.xml
META-INF/leiningen/borkdude/deps.clj/project.clj
META-INF/leiningen/borkdude/deps.clj/README.md
META-INF/leiningen/borkdude/deps.clj/LICENSE
META-INF/
META-INF/maven/
META-INF/maven/borkdude/
META-INF/maven/borkdude/deps.clj/
META-INF/maven/borkdude/deps.clj/pom.properties
DEPS_CLJ_VERSION
DEPS_CLJ_RELEASED_VERSION
borkdude/
borkdude/deps.clj
```

Also it works for me with this repro:

```
$ clj -Sdeps '{:deps {borkdude/deps.clj {:mvn/version "0.0.9"}}}'
Clojure 1.10.1
user=> (require '[borkdude.deps])
nil
```

Do you have more information? Which version are you using?

**Comment by hugoduncan** [comment]
The jar I have came from clojars (downloaded by dist.exe or clojure via `deps.edn` with `borkdude/deps {:mvn/version "0.0.9"}`), and has the file in the jar.

Is the problem that I am trying to use this with babashka rather than clojure?

```shell
export BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {borkdude/deps.clj {:mvn/version "0.0.9"}}}')
bb
Babashka v0.1.3 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (require 'borkdude.deps)
(require 'borkdude.deps)
java.lang.IllegalArgumentException: Cannot open <nil> as a Reader. [at borkdude/deps.clj, line 15, column 7]
user=> (io/resource "DEPS_CLJ_VERSION")
(io/resource "DEPS_CLJ_VERSION")
nil
user=> (io/resource "deps_clj_version")
(io/resource "deps_clj_version")
nil
```

```
-rw-rw-rw-       122   2-Jun-2020  21:06:26  meta-inf/manifest.mf
  -rw-rw-rw-      2251   2-Jun-2020  21:06:26  META-INF/maven/borkdude/deps.clj/pom.xml
  -rw-rw-rw-      1092   2-Jun-2020  21:06:26  META-INF/leiningen/borkdude/deps.clj/project.clj
  -rw-rw-rw-      9205   2-Jun-2020  21:06:26  META-INF/leiningen/borkdude/deps.clj/README.md
  -rw-rw-rw-     11514   2-Jun-2020  21:06:26  META-INF/leiningen/borkdude/deps.clj/LICENSE
  drwxrwxrwx         0   2-Jun-2020  21:06:26  meta-inf/
  drwxrwxrwx         0   2-Jun-2020  21:06:26  META-INF/maven/
  drwxrwxrwx         0   2-Jun-2020  21:06:26  META-INF/maven/borkdude/
  drwxrwxrwx         0   2-Jun-2020  21:06:26  META-INF/maven/borkdude/deps.clj/
  -rw-rw-rw-       142   2-Jun-2020  21:06:26  META-INF/maven/borkdude/deps.clj/pom.properties
  -rw-rw-rw-         5   2-Jun-2020  21:06:24  deps_clj_version
  -rw-rw-rw-         5   2-Jun-2020  21:06:24  deps_clj_released_version
  drwxrwxrwx         0   2-Jun-2020  21:06:24  borkdude/
  -rw-rw-rw-     22355   2-Jun-2020  21:06:24  borkdude/deps.clj

```

**Comment by borkdude** [comment]
@hugoduncan Ah, that's interesting! With babashka you can just run the self-contained script which is located at the root of this repo:

https://github.com/borkdude/deps.clj/blob/master/deps.clj

Just place that script somewhere on your path and if you have bb installed, you should be good to go with `$ deps.clj -Spath ...` etc.
So no need to use a .jar file in that case. I'll take a look at why it behaves this way, regardless.

**Comment by borkdude** [comment]
Just for reference, which OS are you on? Which version of bb?

**Comment by hugoduncan** [comment]
Mac OS Catalina 10.15.6.

I was hoping to use deps.clj as a dependency as part of an uberscript, but the script works for now.

**Comment by borkdude** [comment]
Will be fixed using this PR: https://github.com/borkdude/babashka/pull/529

**Comment by hugoduncan** [comment]
Thinking about it some more, I will still not be able to uberscript it, as, iiuc, resources aren't put in the uberscript.

**Comment by borkdude** [comment]
True. But with a little post-processing that won't be hard to fix.
