### ISSUE TITLE
Windows build is broken.

### ISSUE THREAD

**Issue by aadrian** [borkdude/deps.clj#33]
The windows build is broken - the size of the `deps.clj-0.0.10-windows-amd64.zip` is only 22 bytes.

![deps_dist_broken](https://user-images.githubusercontent.com/140953/94347609-02caa100-0036-11eb-8ceb-e80f178269d5.png)

**Comment by borkdude** [comment]
Thanks. Fix in progress.

**Comment by borkdude** [comment]
Should be fixed now.

**Comment by aadrian** [comment]
@borkdude Thank you. It works great!
