### ISSUE TITLE
Tool downloads files without permission

### ISSUE THREAD

**Issue by 89z** [borkdude/deps.clj#36]
If I run this command:

~~~
java -jar deps.clj-0.0.11-standalone.jar
~~~

This happens:

~~~
Could not find C:\Users\Steven\.deps.clj\1.10.1.763\ClojureTools\clojure-tools-1.10.1.763.jar
Attempting download from https://download.clojure.org/install/clojure-tools-1.10.1.763.zip
Downloading: org/clojure/clojure/1.10.1/clojure-1.10.1.pom from central
Downloading: org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44.pom from central
Downloading: org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176.pom from central
Downloading: org/clojure/pom.contrib/0.2.2/pom.contrib-0.2.2.pom from central
Downloading: org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44.jar from central
Downloading: org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176.jar from central
Downloading: org/clojure/clojure/1.10.1/clojure-1.10.1.jar from central
Clojure 1.10.1
user=>
~~~

I did not give this program permission to download anything, so it should be
asking me first, and not just doing it.

**Comment by borkdude** [comment]
@89z This is a dependency tool similar to the clojure CLI. Its goal is to download dependencies for you. That should be no surprise if you use a dependency tool in my opinion. Also, this tool is used in CI where it would be very unhandy if you had to give permission first.

**Comment by 89z** [comment]
It looks like a REPL to me, based on the end of the output:

~~~
Clojure 1.10.1
user=>
~~~

and based on this:

> Clojure provides the clojure command line tool for:
>
> - Running an interactive REPL (Read-Eval-Print Loop)
> - Running Clojure programs
> - Evaluating Clojure expressions

https://github.com/borkdude/deps.clj

I just think it would makes sense, that if a user want to download something, they can do `deps init` or `deps download`, instead of it being the default action.

**Comment by borkdude** [comment]
@89z Please read https://clojure.org/guides/getting_started. It behaves exactly the same as the `clojure` CLI.

**Comment by borkdude** [comment]
This is a better link to read more about deps.edn and the Clojure CLI: https://clojure.org/guides/deps_and_cli

**Comment by 89z** [comment]
This page:

https://clojure.org/guides/getting_started

can you point out where that is the case? I reviewed the entire page, and I dont see where it talks about automatically downloading missing content without prompting for confirmation.

**Comment by borkdude** [comment]
I posted a better link in the message after that. That page says:

> You will see messages about a library being downloaded the first time you use a dependency. Once the file is downloaded, it will be reused in the future.

**Comment by 89z** [comment]
Ok yes I do see that, thanks.

However just because thats whats done at clojure.org, doesnt mean its a good idea. I work with many programming languages, and this tool is the first tool Ive ever seen, that just starts downloading items without confirmation. With Python, you have `pip install something`. With Ruby, you have `gem install something`. With Go, you have `go get something`.

I just think its bad practice, as the tool can have no idea of a users situation. Maybe they are on a mobile connection, maybe they have no connection at the moment. It just seems better for a user to initialize any downloading. But if you want to defer to whats done on clojure.org, of course thats your decision.

**Comment by borkdude** [comment]
@89z This tool aims to be a (partial) drop-in for the official Clojure tools, so it's designed to do whatever the official tool does.

**Comment by 89z** [comment]
At the very least, would you consider adding a warning to the README? I know it would be duplicating the text already at clojure.org, but I think it would be helpful.

**Comment by borkdude** [comment]
@89z May I ask how you came here and what made you invoke this tool, if you aren't familiar with the "official" clojure tools? That would be useful feedback for me.

**Comment by 89z** [comment]
Sure, I maintain a site of code examples in different programming languages. I
try to support at least 10 different languages.

However recently, I discovered something very unsavory with C#. With perhaps
irony to this issue here, the C# is that the `dotnet` tool is currently secretly
checking for updates in the background. I came to find out that this behavior
cant even be changed currently. As I was disgusted by this, I am out looking for
a replacement language to support.

Clojure is one of the languages I came across. However the install process is
pretty confusing compares to other languages. First, you have to set about
finding a Java environment. I found this after some hunting:

https://adoptopenjdk.net/installation.html

but even on that site, so many versions that its confusing. Anyway after I setup
Java I try to find Clojure setup. First I find this and its really confusing:

https://github.com/clojure/tools.deps.alpha/wiki/clj-on-Windows

but at the very bottom, I find this link:

https://github.com/borkdude/deps.clj

so it seems like `deps.clj` is a "Clojure environment"? I dont know. All I want
is something where I can run a Clojure script. Something simple.

**Comment by borkdude** [comment]
@89z This is useful feedback, thank you.

Clojure depends on Java and when you have Java installed, you use either leiningen or clojure (or boot, but that build tool is quite inactive) to get your projects going. All of these tools pretty much download dependencies when needed to run something (like a REPL, or a main function).

The install process on Windows depends on Powershell and this is why some people prefer this tool instead, since the Powershell scripts don't work in cmd.exe or have other problems.

If you just need to execute small snippets of Clojure, without wanting to install a JVM, you can also try babashka:

https://github.com/babashka/babashka

This is just one binary you will download for your OS and this does not depend on Java. It is a re-implementation of Clojure as a self-contained interpreter, designed for scripting. It should exactly the same for basic Clojure usage, so if you are just learning Clojure, that may be a nice way to get going, if you don't want to install all of the other tools yet.

Sorry for the confusion and thanks again for your feedback.

**Comment by 89z** [comment]
Ok thank very much. I have a couple of questions.

First, Babashka seems like a great option, but is it limited somehow? It just seems too good to be true, not needing a JVM.

Second, it seems its also possible to compile Clojure to native? How is that done? Some command line flag, or is another tool required for the compiling?

**Comment by borkdude** [comment]
@89z 

The trade-off between normal Clojure and babashka is that the JVM and Clojure itself incurs a startup time of about 1-2 seconds, which makes it less suited for small scripts that should start fast. This is where babashka comes in. Babashka is suited for small projects (let's say a few thousand lines) that run for a short amount of time (let's say less then 10 seconds), but performance is not as good. If you have performance critical code, it's better to use the JVM.

Compiling Clojure to native is done through GraalVM native-image. You can find more about that here: https://github.com/lread/clj-graal-docs.
