### ISSUE TITLE
Port to CLJS / Node

### ISSUE THREAD

**Issue by borkdude** [borkdude/deps.clj#37]
This could be useful when a JS / Node based editor wants to launch a tools.deps based project.

**Comment by viebel** [comment]
I think it might be highly valuable in self-hosted web environments like Klipse.
A user would be able to run in Klipse a code snippet that depends on libraries and via deps.clj Klipse will calculate the transitive dependencies to be loaded.

**Comment by borkdude** [comment]
@viebel This project only replaces the bash part of the clojure CLI, not the tools.deps Java backend. So in browsers this won't run. In nodeJS you would invoke a java process much like you would in the bash or this project.

**Comment by borkdude** [comment]
There is now https://github.com/borkdude/nbb as well.
