### ISSUE TITLE
Missing :config-dir entry in -Sdescribe

### ISSUE THREAD

**Issue by Azzurite** [borkdude/deps.clj#38]
When I run this project's `deps` command, I don't see the `:config-dir` key when running `deps -Sdescribe`.

When I do this on the "real" clojure tools it is printed and points to the `~/.clojure` directory.

It should be as simple as adding `[:config-dir config-dir]` below https://github.com/borkdude/deps.clj/blob/0b70844983bf23fff4c2991dadb3fd14c4102b27/src/borkdude/deps.clj#L541

**Comment by borkdude** [comment]
This has been added.
