### ISSUE TITLE
Use `(clojure ...)` in windows

### ISSUE THREAD

**Issue by Jacob-Kroeze** [borkdude/deps.clj#56]
https://github.com/borkdude/deps.clj/blob/565bb8ac4e4519f7ce2ca5c3a7309cf41e2fced5/src/borkdude/deps.clj#L434

A fresh install in windows won't find the file `java.exe`.  e.g running `(clojure -X:,,,)` fails with 

----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  Couldn't find 'java'. Please set JAVA_HOME.

**Comment by borkdude** [comment]
@Jacob-Kroeze Do you have java installed though? What d you get for `where java`?

**Comment by Jacob-Kroeze** [comment]
Yes. This is on an old Azure DevOps on-prem installation, so no easy access to cmd.exe. I was able to set "JAVA_CMD" and bb deps.clj stuff works now.

**Comment by Jacob-Kroeze** [comment]
Maybe this would work out?
```
(let [f (io/file java-home "bin" 
;"java" 
java-cmd)] ...
```

**Comment by borkdude** [comment]
@Jacob-Kroeze I need more info about what the java command on your machine looks like, which is why I asked about `where clojure`. A way to do this in bb is:

```
bb -e "(map str (fs/which-all (str (quote java))))"
```

My suspicion is that your Java ends with `.cmd` or so, and deps.clj doesn't take this into account yet.

**Comment by Jacob-Kroeze** [comment]
Hi @borkdude, it's great to finally use bb to make a build easy!

On the windows agent build server, `fs/which-all` doesn't find java. 
Also, I noticed `fs/exec-paths` doesn't have the agent's  `$JAVA_HOME\\bin` on the path, so I don't think `fs/which` would find java anyway.

On my windows desktop, `fs/exec-paths` has `$JAVA_HOME\\bin` on the path and `fs/which` and `fs/which-all` finds java as expected.

**Comment by borkdude** [comment]
@Jacob-Kroeze Thanks! What is the output of `(fs/which "java")` without any extensions? An empty collection? Are you sure that Java is installed there, because this sounds really curious to me. 

Maybe @bobisageek has an idea?

**Comment by Jacob-Kroeze** [comment]
Hi @borkdude, it's great to finally use bb to make a build easy!

On the windows agent build server, `fs/which-all` doesn't find java. 
Also, I noticed `fs/exec-paths` doesn't have the agent's  `$JAVA_HOME\\bin` on the path, so I don't think `fs/which` would find java anyway.

On my windows desktop, `fs/exec-paths` has `$JAVA_HOME\\bin` on the path and `fs/which` and `fs/which-all` finds java as expected.

I think this would fix for myself:

https://github.com/Jacob-Kroeze/deps.clj/blob/158d86ab304aea5e5f0740a66f7402d607bc325b/src/borkdude/deps.clj#L434

**Comment by borkdude** [comment]
Sounds good, PR welcome

**Comment by borkdude** [comment]
This was already fixed
