### ISSUE TITLE
Replicate use of new  CLJ_JVM_OPTS and JAVA_OPTS environment variables from ClojureTools

### ISSUE THREAD

**Issue by ikappaki** [borkdude/deps.clj#58]
These were added in clojure tools script in 1.11.1.1165 as https://github.com/clojure/brew-install/commit/7914954030ca21f7b928b6f064ace086efdc9057 with https://clojure.atlassian.net/browse/TDEPS-165

See https://ask.clojure.org/index.php/12190/certificate-exception-downloading-dependencies-firewall for the use case. Basically it allows the user to pass java properties to allow it to reference extra certificates which might be required for Internet connectivity.

These two variables allow the user to pass extra jvm parameters at depency resolution (``CLJ_JVM_OPTS``) and when running the repl/program (`JAVA_OPTS`) with the clojure tools wrapper.

In addition to the above, `deps.clj` also does a direct connection to the Internet to download the clojure tools. These two variables are not consulted in this process. Thus if the intention is to use any of the variables to select an alternative certificate store for connecting to the internet, deps.clj will not know about that.

Available options to consult the properties defined at the variables are:
1. At run time look at the variables, extract the JVM properties and do `System/setProperty`. This will not work because the `javax.net.ssl.*` properties have to be applied at start up.
2. Invoke an external java program to download the clojure tools, and pass the `CLJ_JVM_PARAMS` to it as command line arguments.
3. Let the application which invokes the deps.clj tools pass in to the `java` invocation the necessary java `javax.net.ssl.*` properties

Happy to do a PR for this.

Thanks

**Comment by borkdude** [comment]
PR welcome
