### ISSUE TITLE
Add build instructions to README

### ISSUE THREAD

**Issue by sundbp** [borkdude/deps.clj#6]
I see some hints in the circle-ci config, but it'd be great to have some development workflow comments in the README. I'm looking to add support for it picking up http proxy info from the environment if available and some instructions would smooth out the process to test it out locally.

Thanks for a great initiative!

**Comment by borkdude** [comment]
Hi @sundbp,

For running it locally, you can just do:

```
$ clojure -m borkdude.deps -Spath
```

or:

```
$ lein run -m borkdude.deps -Spath
```

To run jvm tests:

```
$ script/jvm_test
```

To run with babashka after making changes to `src/borkdude/deps.clj`, you should run:

```
$ script/gen_script.clj
```

and then:

```
$ ./deps.clj -Spath
# or
$ bb deps.clj -Spath
```

To run as an executable, you'll have to run:

```
$ script/build
```

and to run executable tests:

```
$ script/exe_test
```

CircleCI does all of this already, so for local development it's probably fine to only use the JVM or babashka and let the tests be run on CircleCI for the other stuff as well.

**Comment by sundbp** [comment]
Thanks - that's all I needed. You can probably copy paste some of that into
a new Development section of the readme. Cheers.
