### ISSUE TITLE
Improve MS-Windows dev/ci support

### ISSUE THREAD

**Issue by ikappaki** [borkdude/deps.clj#61]
Hi,

while working on the previous PR, I've noticed that MS-Windows build  support is subpar with the Linux and macos build:
1. There are a few tests that excluded from running on windows, e.g. `jvm-opts-test`,
2. There was no `.bat` equivalent for `script/jvm_test` ,
3. Windows testing invocation is missing from `appveyor.yml`.

Thus I would like to propose we fix the missing tests from windows, include windows testing in CI, and as I bonus move all scripts into `bb.edn`.

Happy to look into all of these.

Thanks

**Comment by borkdude** [comment]
@ikappaki Improvements welcome!

**Comment by ikappaki** [comment]
Hi @borkdude,

I'm considering doing the following next if you please indicate you are ok or not for me proceed with new PRs:
1. Update circleci to run  `jvm-test` and `babshka-test` on all `[macos, ubuntu, windows]`x`[java 8, 11, 15, 17]`. I want to make sure that we capture any potential differences across all these archs and java version. This is because of the unexpected quoting difference seen in windows/Java 17 vs previous java versions while enabling the `main opts` tests on windows with an earlier PR.
2. Upgrade graalvm version to latest 22.2.0 version.

Thanks,

**Comment by borkdude** [comment]
@ikappaki Sure. But we could just generate the circleci configuration from an .EDN file then and do the matrix programmatically (instead of using CircleCI specific stuff). What do you think of that idea?
See e.g. babashka and https://github.com/babashka/babashka-sql-pods for EDN -> CircleCI YAML examples.

Upgrading GraalVM: yes, we could do that in a separate PR maybe.

**Comment by borkdude** [comment]
@ikappaki I just found out how to do a matrix on appveyor with different JDK versions:

https://github.com/babashka/nbb/blob/f876bef6bb8170cdf7b8ce47a1f861c0308abf53/appveyor.yml#L10-L13

https://github.com/babashka/nbb/blob/main/appveyor.yml#L38-L39

So we might just be able to do it on Appveyor + Circle without much rewriting. Here is a fuller example of a matrix:

https://github.com/checkstyle/checkstyle/blob/5a8bcfc381ec2695cf1f64bd1e46335492a17a92/appveyor.yml#L41-L53

**Comment by borkdude** [comment]
I think we can close this now that we have GH actions running tests. Feel free to comment when it should be re-opened.
