### ISSUE TITLE
split -main into `calculation of main-args` and `starting java` ?

### ISSUE THREAD

**Issue by behrica** [borkdude/deps.clj#77]
In the context of `libpython-clj` in embedded mode we need to tell python to start a java JVM including Clojure.
So we call this python function of javabridge at a certain moment:

https://github.com/CellProfiler/python-javabridge/blob/2d8816340c5e1abf0e85f08f96f162e0614c1d8a/javabridge/jutil.py#L203

Ideally the classpath and the JVM args passed in should be the same as "real Clojure" generates from a deps.edn.

I am wondering if we could use a modified version of `deps.clj` and use it **as a library** to calculate the class path and the JVM args and return them , without starting the JVM.

This would require to split the `main-` function into `calculating` of the main-args and `starting of the JVM`.
This would then allow us to call the `calculate classpath and JVM args` and pass them to the python function above, which then starts the JVM in the python context.

Do you think this is feasible ?

We have a very primite "JVM starter" here, 
https://github.com/behrica/clojurebridge/blob/2c3c6e6c6d3d74f61aa2d68d7bf1c770d76b09cc/src/clojurebridge/cljbridge.py#L159

but it is not full featured, compared to deps.clj, specially it does not allow to pass any JVM arguments.

It seems to me that this requires only a small refactoring of 
(defn -main

into 2 functions.
1. A pure function, just calculating the JVM arguments and returns them
(but as a map which we can further use, specially do understand what is classpath and what is JVM args
and not as a vector of strings)
2. A non-pure function, which use teh above and starts the JVM

**Comment by behrica** [comment]
No, I have not  looked at tools.build.

I will check it and see, if it provides what we need.

**Comment by borkdude** [comment]
OK, please report back here when you're done checking so we can either implement or close this issue.

**Comment by behrica** [comment]
I checked, and saw some entry points like:

https://github.com/clojure/tools.deps.alpha/blob/48d3a57c22ac6b4a229aa6eb070606ddb0f3d1c7/src/main/clojure/clojure/tools/deps/alpha/script/make_classpath2.clj#L78

But that takes a lot of input, and I have the impression that by using it I would need to re-implement half of what `deps.clj` does.

I have a half-backed local modification of deps.clj and I attach you the diff.

This is not ready by no mean for a PR, but it shows how this split could be done, witthout changing the current functionality of `deps.clj`

**Comment by behrica** [comment]
```diff
diff --git a/deps.clj b/deps.clj
index 8079a72..eab0f4c 100755
--- a/deps.clj
+++ b/deps.clj
@@ -308,8 +308,8 @@ For more info, see:
   {"-J" :jvm-opts
    "-R" :resolve-aliases
    "-C" :classpath-aliases
-   "-A" :repl-aliases
-   })
+   "-A" :repl-aliases})
+   
 
 (def bool-opts->keyword
   {"-Spath" :print-classpath
@@ -422,7 +422,7 @@ For more info, see:
     (.relativize (as-path dir) (as-path f))
     f))
 
-(defn -calc-args [& command-line-args]
+(defn -main [& command-line-args]
   (let [opts (parse-args command-line-args)
         java-cmd
         (or (System/getenv "JAVA_CMD")
@@ -691,44 +691,21 @@ For more info, see:
                     cp (if (or exec? tool?)
                          (str cp path-separator exec-cp)
                          cp)
-                    main-args-map {:java-cmd [java-cmd]
-                                   :proxy-settings proxy-settings
-                                   :jvm-cache-opts jvm-cache-opts
-                                   :jvm-opts (:jvm-opts opts)
-                                   :clojure-jvm-opts [(str "-Dclojure.basis=" (relativize basis-file))
-                                                      (str "-Dclojure.libfile=" (relativize libs-file))]
-                                   :classpath cp
-                                   :args (:args opts)
-                                   }
                     main-args (concat [java-cmd]
                                       proxy-settings
                                       jvm-cache-opts
                                       (:jvm-opts opts)
                                       [(str "-Dclojure.basis=" (relativize basis-file))
-                                       (str "-Dclojure.libfile=" (relativize libs-file))]
-                                      ["-classpath" cp]
-                                      ["clojure.main"]
+                                       (str "-Dclojure.libfile=" (relativize libs-file))
+                                       "-classpath" cp
+                                       "clojure.main"]
                                       main-opts)
                     main-args (filterv some? main-args)
                     main-args (into main-args (:args opts))]
                 (when (and (= :repl mode)
                            (pos? (count (:args opts))))
                   (warn "WARNING: Implicit use of clojure.main with options is deprecated, use -M"))
-                {:main-args main-args
-                 :main-args-map main-args-map}
-                ;; (println :main-args main-args)
-                ))))))
-
-(defn -main  [& command-line-args]
-  (let [calculaed-args (-calc-args command-line-args)]
-    (clojure.pprint/pprint (:main-args-map calculaed-args))
-    (*process-fn* {:main-args calculaed-args})
-    )
-  )
-
-
-
-(comment
-  (-calc-args []))
+                (println :main-args main-args)
+                (*process-fn* main-args)))))))
 
 (apply -main *command-line-args*)
diff --git a/src/borkdude/deps.clj b/src/borkdude/deps.clj
index 1e58f43..5560efd 100755
--- a/src/borkdude/deps.clj
+++ b/src/borkdude/deps.clj
@@ -424,7 +424,7 @@ For more info, see:
     (.relativize (as-path dir) (as-path f))
     f))
 
-(defn -calc-args [& command-line-args]
+(defn -calc-args [command-line-args]
   (let [opts (parse-args command-line-args)
         java-cmd
         (or (System/getenv "JAVA_CMD")
@@ -717,10 +717,12 @@ For more info, see:
                 (when (and (= :repl mode)
                            (pos? (count (:args opts))))
                   (warn "WARNING: Implicit use of clojure.main with options is deprecated, use -M"))
-                 {:main-args main-args
-                 :main-args-map main-args-map}
                 (println :main-args main-args)
-                ))))))
+                {:main-args main-args
+                 :main-args-map main-args-map})
+
+
+)))))
 
 (defn -main  [& command-line-args]
   (let [calculated-args (-calc-args command-line-args)]
@@ -730,6 +732,5 @@ For more info, see:
   )
 
 
-
 (comment
   (def calculated-args  (-calc-args [])))
```

**Comment by borkdude** [comment]
@behrica Just to be sure we're on the same page. 

I meant https://github.com/clojure/tools.build, not tools.deps.alpha

**Comment by behrica** [comment]
Yes, this API i looked at:

https://clojure.github.io/tools.build/

None of the functions will return me the complete JAVA opts,
starting from a list of aliases.

They do this for calculating the complete class path, but not for teh complete args to teh java command.

Maybe an example makes it clear:

if I have aliases  like this:
```
 :add-foreign
  {:jvm-opts ["--add-modules" "jdk.incubator.foreign"
              "--enable-native-access=ALL-UNNAMED"]}
 :x
  {:jvm-opts ["--Dx=test"]}

```

I would like a library function which returns me  "--add-modules" "jdk.incubator.foreign --enable-native-access=ALL-UNNAMED  --Dx=test   telling it the aliases I want to activate ["add-foreign" "x"]

And it should do this as "clojure" does. So looking in the same places for alias definitions and merge them using the standard rules.

`deps.clj` does this, because it passes those to the java invocation.

But indeed, I am not 100 % how it does it. I saw calls to  `clojure.tools.deps.alpha.script.generate-manifest2"`, but they are not pure functions, they write staff to disk, which I don't want. And to call them seems complicated. I would like to have a function which only takes the aliases to activate as input and returns me ALL pieces needed to  start the java process (but does not start it)

Or otherwise said , a function which takes all "input options of the clojure programm", calculates classpth + java arguments and return those.
(this is the -main in deps.clj, except that it starts as well the java process, which I don't want.) I will tell python to start java.


I need 2 pieces of information:
- the full classpath (this would be possible with `tools.build`
- teh "resolved" args to `java` (apart from classpath)     - for this I have not seen a function yet

**Comment by borkdude** [comment]
@behrica I'm fine with an initial experimental PR to deps.clj, extracting some things in a function that we can expose. Then we can discuss the next step.

**Comment by behrica** [comment]
> OK, please report back here when you're done checking so we can either implement or close this issue.

I looked again into it, after reding some comments.

And ~clojure.tools.build.api` has all what is needed:

```
 (ns user
   (:require [libpython-clj2.python :as py]
             [clojure.tools.build.api :as b]))


(def basis (b/create-basis {:aliases [:jdk-17 :fastcall]}))

(def java-args
  (b/java-command {:basis basis
                   :java-opts (:jvm-opts (:resolve-args basis))
                   :main "hello"}))

java-args
```

So for my purposes the changes in PR #78  are not needed any more.

**Comment by borkdude** [comment]
That is what I already figured. Thanks.
