### ISSUE TITLE
Installation with MacOS M2.

### ISSUE THREAD

**Issue by deafjava** [borkdude/deps.clj#87]
This instruction, I ran with MacOS, M2 (just giving what was the machine, I don't think the architecture influenced):
```shell
$ bash <(curl -s https://raw.githubusercontent.com/borkdude/deps.clj/master/install)
$ deps
Clojure 1.10.1
user=>
```
I got, that had to run with superadmin:
```shell
sudo bash <(curl -s https://raw.githubusercontent.com/borkdude/deps.clj/master/install)
Password:
bash: /dev/fd/11: Bad file descriptor
```

The workaround I put:
```shell
curl -s https://raw.githubusercontent.com/borkdude/deps.clj/master/install -o install_deps_clj.sh
chmod +x install_deps_clj.sh
sudo ./install_deps_clj.sh
```
Then successfully installed deps in /usr/local/bin.

An issue?

**Comment by borkdude** [comment]
Yes, I think this is mostly a documentation problem. If `/usr/local/bin` isn't writeable you must use `sudo`. PR welcome to update.

**Comment by deafjava** [comment]
Oh, I missed this message! Thank you! Doing it.

**Comment by deafjava** [comment]
If you want I open a PR, I would need to be granted permission for it.

**Comment by borkdude** [comment]
Fixed the docs now hopefully.
