### ISSUE TITLE
Expose paths to (at least) basis file via API

### ISSUE THREAD

**Issue by cursive-ide** [borkdude/deps.clj#98]
When using the new API in Cursive, the main thing I need to obtain is the path to the basis file for a particular configuration. Currently I'm calculating this myself, but it requires the checksum for the configuration which is private and not documented as part of the API. However, the checksum is really just an implementation detail, so if the API exposed the basis file path instead then I wouldn't need the checksum. 

I'm not sure if other users might potentially need access to other files, perhaps the classpath one might be required by clients starting a process of some kind using deps?

**Comment by borkdude** [comment]
I exposed `get-basis-file` and `get-checksum` now on master. Do you need a new clojars release?

**Comment by cursive-ide** [comment]
I can work with a local copy in the meantime if you're planning to add more things to the release, but I'll need one before releasing this work in Cursive.

**Comment by borkdude** [comment]
OK, please test locally and then I'll make a release
